- hosts: all
  tasks:  
    - name: modify grub file
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX(.*)"$'
        line: 'GRUB_CMDLINE_LINUX\1 net.ifnames=0 biosdevname=0"'
        backrefs: yes
    - name: read grub config
      ansible.builtin.command: grub2-mkconfig
